### ISSUE TITLE
manifest tracking

### ISSUE THREAD

**Issue by AshtonSBradley** [SimonEnsemble/Controlz.jl#18]
Hi, 

First, great package! 

Small issue: I had to remove it because it was holding Plots back on my system. Bizarre because Plots isn't in your Project.toml. Is this because you are tracking Manifest.toml? Maybe its nothing to do with your package... You probably have a good reason (?) but checking in Manifest.toml  with your repo is likely not required, and will cause issues for other packages...

Thanks, and sorry for the noise if this isn't relevant

**Comment by SimonEnsemble** [comment]
thank you for praise and for reporting this!

`Plots.jl` (not `PyPlot.jl`) was held back? right, `Plots` is not used by `Controlz.jl` so must be a dependency of `Plots` that was held back. still, bad news.

in my `Project.toml` [here](https://github.com/SimonEnsemble/Controlz.jl/blob/master/Project.toml#L16-L22) I only specify `package == x.x.x`, which according to [this](https://julialang.github.io/Pkg.jl/v1/compatibility/#Compatibility-1) does not mean "exactly version x.x.x". do you know in particular which package is causing issues? Maybe e.g. I put `package = 0.2.3" and `Plots.jl` needs v`1.0.0`, which is restricted by my `Project.toml`?

the `Manifest.toml` I recall was machine-generated. you're saying that I don't need this? to be honest, this `Manifest.toml` is a mystery to me as to what it does...

**Comment by SimonEnsemble** [comment]
I'm reading that the `Manifest.toml` is optional in case you want to severely restrict/ precisely control the package environment... I understand.

e.g. `DifferentialEquations.jl` does not even have a `Manifest.toml` [here](https://github.com/SciML/DifferentialEquations.jl), so I can safely delete mine. thanks!

**Comment by SimonEnsemble** [comment]
see https://github.com/SimonEnsemble/Controlz.jl/commit/b5f191c1525b3e9375cec8da4e640517cbd40c08. please lmk if this does not solve the issue! thanks for reporting.

**Comment by AshtonSBradley** [comment]
I must admit I couldn't entirely tell which dependency of Controlz was holding back Plots. It was held back to 0.26, while current is 1.4... I suppose a dependency might also have a manifest checked in that is well out of date? Anyway, glad that helped. Cheers
