### ISSUE TITLE
Failed to precompile 

### ISSUE THREAD

**Issue by AliRAlroomi** [SimonEnsemble/Controlz.jl#20]
I have tried to install Controlz package by following the same steps given in the official page. After I installed PyPlot and tried to test matplotlib (it is already installed with Python 3.x), I got the following error (with qt):

[ Info: Installing matplotlib via the Conda matplotlib package...
[ Info: Running `conda install -y matplotlib` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\User-PC\.julia\conda\3

  added / updated specs:
    - matplotlib

The following NEW packages will be INSTALLED:

  cycler             pkgs/main/win-64::cycler-0.10.0-py38_0
  freetype           pkgs/main/win-64::freetype-2.10.2-hd328e21_0
  icu                pkgs/main/win-64::icu-58.2-ha925a31_3
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  kiwisolver         pkgs/main/win-64::kiwisolver-1.2.0-py38h74a9793_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            pkgs/main/win-64::libtiff-4.1.0-h56a325e_1
  lz4-c              pkgs/main/win-64::lz4-c-1.9.2-h62dcd97_1
  matplotlib         pkgs/main/win-64::matplotlib-3.3.1-0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.3.1-py38hba9282a_0
  olefile            pkgs/main/noarch::olefile-0.46-py_0
  pillow             pkgs/main/win-64::pillow-7.2.0-py38hcc1f983_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.7-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py38ha925a31_4
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  sip                pkgs/main/win-64::sip-4.19.13-py38ha925a31_0
  tk                 pkgs/main/win-64::tk-8.6.10-he774522_0
  tornado            pkgs/main/win-64::tornado-6.0.4-py38he774522_1
  xz                 pkgs/main/win-64::xz-5.2.5-h62dcd97_0
  zstd               pkgs/main/win-64::zstd-1.4.5-h04227a9_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Users\User-PC\.julia\conda\3\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

ERROR: LoadError: InitError: failed process: Process(setenv(`'C:\Users\User-PC\.julia\conda\3\Scripts\conda.exe' install -y matplotlib`,["PATH=C:\\Users\\User-PC\\.julia\\conda\\3\\Library\\bin;C:\\Users\\User-PC\\.julia\\conda\\3\\Library\\bin;C:\\Users\\User-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\Scripts\\;C:\\Users\\User-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\;C:\\Users\\User-PC\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\User-PC\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\PTW32\\BIN", "USERDOMAIN_ROAMINGPROFILE=ALROOMI", "VRAY30_RT_FOR_3DSMAX2014_PLUGINS_X64=C:\\Program Files\\Chaos Group\\V-Ray\\RT for 3ds Max 2014 for x64/bin/plugins", "IVIROOTDIR32=C:\\Program Files (x86)\\IVI Foundation\\IVI\\", "HOMEPATH=\\Users\\User-PC", "CM2014DIR=C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\", "NIEXTCCOMPILERSUPP=C:\\Program Files (x86)\\National Instruments\\Shared\\ExternalCompilerSupport\\C\\", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "NODE_ENV=production", "SESSIONNAME=Console"  …  "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "ILMDIR=C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\", "CONDA_PREFIX=C:\\Users\\User-PC\\.julia\\conda\\3", "ATOM_HOME=C:\\Users\\User-PC\\AppData\\Local\\JuliaPro-1.5.0-1\\.atom", "FPS_BROWSER_USER_PROFILE_STRING=Default", "MINITAB_LICENSE_FILE=C:\\Program Files (x86)\\Minitab\\Minitab 17;C:\\Program Files (x86)\\Minitab\\Minitab 18", "SYSTEMDRIVE=C:", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at .\process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at .\process.jl:440
 [3] run at .\process.jl:438 [inlined]
 [4] runconda(::Cmd, ::String) at C:\Users\User-PC\.julia\packages\Conda\3rPhK\src\Conda.jl:114
 [5] add(::String, ::String; channel::String) at C:\Users\User-PC\.julia\packages\Conda\3rPhK\src\Conda.jl:188
 [6] add at C:\Users\User-PC\.julia\packages\Conda\3rPhK\src\Conda.jl:187 [inlined] (repeats 2 times)
 [7] pyimport_conda(::String, ::String, ::String) at C:\Users\User-PC\.julia\packages\PyCall\zqDXB\src\PyCall.jl:699
 [8] pyimport_conda at C:\Users\User-PC\.julia\packages\PyCall\zqDXB\src\PyCall.jl:693 [inlined]
 [9] __init__() at C:\Users\User-PC\.julia\packages\PyPlot\XHEG0\src\init.jl:179
 [10] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
 [11] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:782
 [12] _require(::Base.PkgId) at .\loading.jl:1007
 [13] require(::Base.PkgId) at .\loading.jl:928
 [14] require(::Module, ::Symbol) at .\loading.jl:923
 [15] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1088
during initialization of module PyPlot
in expression starting at untitled-e8d43f8d04b8aa6e8bd173b926303540:1

**Comment by SimonEnsemble** [comment]
looks like your system is having trouble installing `PyPlot`. can you try to `] add PyPlot` and `using PyPlot`? once you properly install that package, Controlz.jl should work!
