### ISSUE TITLE
matplotlib dependency

### ISSUE THREAD

**Issue by eahenle** [SimonEnsemble/Controlz.jl#29]
migrate to `Makie.jl` to eliminate Python dep?

**Comment by SimonEnsemble** [comment]
yes, good idea! this will reduce installation issues students have. I will do that over winter break. :) so you can hold off on making a [probably complicated, to handle Python] CI PR on this and I will just ask you questions if I need help mimicking `Xtals.jl` in a couple of months. thx!

**Comment by SimonEnsemble** [comment]
done!
