### ISSUE TITLE
Making some JuliaAcademy Materials

### ISSUE THREAD

**Issue by logankilpatrick** [SimonEnsemble/Controlz.jl#6]
Hey @CorySimon ! @viralbshah suggested that it would be awesome if we could work together on making a JuliaAcademy course on this package. 

Maybe something like a 5 part, 10-minute videos each with a notebook that just walks through a few of the different examples you have in your docs and talks about the why and how to use those examples or function. After that, we would post it to JuliaAcademy.com ! I can help work through the logistics of this if you are interested.

IMO, the course would be approached from the standpoint of someone who has never heard of your package but wants to use it. So an introductory 5-10 minute video talking about maybe why you built the package, who it's being used by, and maybe future development and such.

**Comment by SimonEnsemble** [comment]
@logankilpatrick Yes, that would be great! This would benefit my class, too. I'm also creating weekly studio modules using Controlz.jl, e.g. [here](https://nbviewer.jupyter.org/github/SimonEnsemble/control_theory_demos/blob/master/studios/intro%20to%20transfer%20functions.ipynb), so there will, by the time I'm done with the class, be a lot of free content online for learning control theory (for chemical engineers, at least).

I think a good outline might be:
1. constructing transfer functions
2. transfer function algebra and characterization
3. simulating the response to an input
4. simulating the response to two inputs
5. simulating a closed-loop, PID feedback control system

Is your plan to have the complete course done, *then* post, or post one module at a time? How should we proceed, and what is the timeline for doing this? Thanks!

**Comment by ViralBShah** [comment]
There's no timeline as such. The hope is to keep adding more materials to JuliaAcademy over time.

I think it would greatly help to have complete classes loaded in there, when they are ready.
